const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n);
const num=(n,d=1)=>Number(n).toFixed(d);
let DATA={};
async function load(){
  const [bill,tesla,emporia,solaredge]=await Promise.all(['bill','tesla','emporia','solaredge'].map(x=>fetch(`data/${x}.json?v=1`).then(r=>r.json())));
  DATA={bill,tesla,emporia,solaredge}; render();
}
function render(){
 const {bill:b,tesla:t,emporia:e,solaredge:s}=DATA;
 $('#account-balance').textContent=money(b.trueup.account_balance); $('#trueup-date').textContent=new Date(b.true_up+'T12:00:00').toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'});
 $('#nem-balance').textContent=money(b.trueup.nem_balance); $('#nbc-balance').textContent=money(b.trueup.non_bypassable_charges); $('#other-balance').textContent=money(b.trueup.other_meter_charges_payments); $('#month-charge').textContent=money(b.current_period.current_charges);
 $('#confidence').textContent='82%';
 const E=t.energy; $('#t-solar').textContent=`${num(E['Solar (kW)'])} kWh`; $('#t-home').textContent=`${num(E['Home (kW)'])} kWh`; $('#t-grid').textContent=`${num(E['Grid (kW)'])} kWh`; $('#t-battery').textContent=`${num(E['Powerwall (kW)'])} kWh`;
 $('#tesla-range').textContent=`through ${new Date(t.range.end).toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit'})}`;
 ['Solar','Home','Battery','Grid'].forEach(k=>$('#map'+k).textContent='');
 $('#mapSolar').textContent=`${num(E['Solar (kW)'])} kWh`; $('#mapHome').textContent=`${num(E['Home (kW)'])} kWh`; $('#mapBattery').textContent=`${num(E['Powerwall (kW)'])} kWh net`; $('#mapGrid').textContent=`${num(E['Grid (kW)'])} kWh net`;
 $('#evJuly').textContent=num(e.summary.july_kwh,1); $('#sdgePeak').textContent=`${num(b.current_period.highest_demand_kw,1)} kW`; $('#evPeak').textContent=`${num(e.summary.july18_midnight_kwh,2)} kWh`;
 const share=e.summary.july18_midnight_kwh/b.current_period.highest_demand_kw*100; $('#evShare').style.width=Math.min(100,share)+'%'; $('#evExplainer').textContent=`The EV charger accounts for about ${num(share,0)}% of the utility's 14.4 kW highest-use hour. The remaining ~${num(b.current_period.highest_demand_kw-e.summary.july18_midnight_kwh,1)} kW came from the rest of the home.`;
 drawNem(); drawTesla(); drawEv(); drawDonut(); renderTou(); renderAudit(); renderInsights(); renderConnections();
 const winterPeak=Math.max(...b.months.map(x=>x.balance));
 $('#topInsight').innerHTML=`<h3>✦ Build 1 finding: winter created the problem, summer is clawing it back.</h3><p>Your running NEM balance peaked at <b>${money(winterPeak)}</b> in March, then fell to <b>${money(414.17)}</b> by July as spring/summer exports produced credits. The current $910.02 account balance is not the same thing as $910 of energy purchases.</p>`;
}
function canvasSetup(id){const c=$(id),dpr=devicePixelRatio||1,w=c.clientWidth,h=+c.getAttribute('height');c.width=w*dpr;c.height=h*dpr;const x=c.getContext('2d');x.scale(dpr,dpr);return {c,x,w,h}}
function drawNem(){const {x,w,h}=canvasSetup('#nemChart'),m=DATA.bill.months,p=26; x.clearRect(0,0,w,h);const maxK=Math.max(...m.map(d=>Math.abs(d.net_kwh))),maxB=Math.max(...m.map(d=>d.balance)); const step=(w-p*2)/(m.length-1); x.strokeStyle='#292930';x.lineWidth=1;for(let i=0;i<4;i++){let y=p+i*(h-p*2)/3;x.beginPath();x.moveTo(p,y);x.lineTo(w-p,y);x.stroke()} m.forEach((d,i)=>{const barH=Math.abs(d.net_kwh)/maxK*58,xx=p+i*step,base=h-46;x.fillStyle=d.net_kwh<0?'#48d17a':'#8a7cff';x.fillRect(xx-7,d.net_kwh<0?base:base-barH,14,barH);x.fillStyle='#777780';x.font='9px sans-serif';x.textAlign='center';x.fillText(new Date(d.date+'T12:00:00').toLocaleDateString('en-US',{month:'short'}),xx,h-15)}); x.strokeStyle='#64d8ff';x.lineWidth=2.5;x.beginPath();m.forEach((d,i)=>{const xx=p+i*step,yy=p+(1-d.balance/maxB)*(h-85);i?x.lineTo(xx,yy):x.moveTo(xx,yy)});x.stroke()}
function drawTesla(){const {x,w,h}=canvasSetup('#teslaChart'),s=DATA.tesla.series,p=16,keys=[['solar','#ffcb66'],['home','#f5f5f7'],['grid','#64d8ff']];const max=Math.max(...s.flatMap(r=>keys.map(([k])=>Math.abs(r[k]||0))));keys.forEach(([k,col])=>{x.strokeStyle=col;x.globalAlpha=.9;x.lineWidth=1.5;x.beginPath();s.forEach((r,i)=>{const xx=p+i*(w-p*2)/(s.length-1),yy=h-p-(Math.max(0,r[k]||0)/max)*(h-p*2);i?x.lineTo(xx,yy):x.moveTo(xx,yy)});x.stroke()});x.globalAlpha=1}
function drawEv(){const {x,w,h}=canvasSetup('#evChart'),d=DATA.emporia.daily,p=18,max=Math.max(...d.map(v=>v.kwh));d.forEach((r,i)=>{const xx=p+i*(w-p*2)/d.length,bh=r.kwh/max*(h-45);x.fillStyle=r.kwh>0?'#8a7cff':'#24242a';x.fillRect(xx,h-22-bh,Math.max(2,(w-p*2)/d.length-2),bh)});x.fillStyle='#777780';x.font='9px sans-serif';x.fillText('Jul 1',p,h-7);x.textAlign='right';x.fillText('Aug 19',w-p,h-7)}
function drawDonut(){const {x,w,h}=canvasSetup('#donut'),b=DATA.bill.trueup,vals=[b.nem_balance,b.non_bypassable_charges,b.other_meter_charges_payments],cols=['#8a7cff','#64d8ff','#ffb84d'],sum=vals.reduce((a,b)=>a+b,0);let a=-Math.PI/2;vals.forEach((v,i)=>{const z=v/sum*Math.PI*2;x.beginPath();x.strokeStyle=cols[i];x.lineWidth=24;x.arc(w/2,h/2,78,a,a+z);x.stroke();a+=z});$('#donutTotal').textContent=money(sum);$('#breakdown').innerHTML=[['NEM energy',vals[0]],['Non-bypassable',vals[1]],['Other meter',vals[2]]].map((r,i)=>`<div class="break-row"><i class="dot"></i><small>${r[0]}</small><b>${money(r[1])} · ${num(r[1]/sum*100,0)}%</b></div>`).join('')}
function renderTou(){const b=DATA.bill.current_period,rows=[['On-peak',b.on_peak_kwh],['Off-peak',b.off_peak_kwh],['Super off-peak',b.super_off_peak_kwh]],max=Math.max(...rows.map(r=>Math.abs(r[1])));$('#touBars').innerHTML=rows.map(([n,v])=>`<div class="tou-row"><b>${n}</b><div class="track"><i class="fill ${v<0?'export':''}" style="width:${Math.abs(v)/max*100}%"></i></div><strong>${v>0?'+':''}${v} kWh</strong></div>`).join('')}
function renderAudit(){const b=DATA.bill,e=DATA.emporia.summary;const items=[
 ['good','Current-month bill is tiny',`Electric service was ${money(b.current_period.electric_service)} and the climate credit reduced current charges to ${money(b.current_period.current_charges)}.`],
 ['good','Winter drove the running NEM balance','The NEM balance climbed to $684.16 by March, then spring/summer export credits pulled it down to $414.17 in July.'],
 ['good','July 18 demand spike identified',`Emporia shows ${num(e.july18_midnight_kwh,2)} kWh on the EV charger from midnight–1 AM, explaining most of SDG&E's 14.4 kW peak hour.`],
 ['warn','Registered solar system size needs verification',`The bill lists a 6.86 kW NEM system. Verify whether that represents all 29 panels, one array, or the original permitted system.`],
 ['warn','Solar source scope mismatch',`Tesla's supplied Aug 19 export integrates to ~${num(DATA.tesla.energy['Solar (kW)'],1)} kWh solar through 8:35 PM, while the supplied SolarEdge share snapshot reports ${DATA.solaredge.reported_today_kwh} kWh today. That may mean separate arrays or different metering boundaries; Build 1 flags it instead of guessing.`]
 ];$('#auditTrail').innerHTML=items.map(([c,h,p])=>`<div class="time-item ${c}"><b>${h}</b><span>${p}</span></div>`).join('')}
function getInsights(){const b=DATA.bill,e=DATA.emporia.summary,t=DATA.tesla.energy,s=DATA.solaredge;return [
 {p:1,t:'Verify the 6.86 kW registered NEM system',d:'With 29 panels, the registered system size deserves a permit/interconnection check. It may be correct if panels are older/smaller, or it may represent only part of the current system.'},
 {p:1,t:'Map the two solar views before trusting production totals',d:`Tesla estimates ${num(t['Solar (kW)'],1)} kWh on the supplied day through 8:35 PM, while SolarEdge reports ${s.reported_today_kwh} kWh. The platform should treat SolarEdge and Tesla as separate meters until their scope is confirmed.`},
 {p:2,t:'EV charging timing looks rate-aware',d:`The July 18 EV spike began at midnight, inside EV-TOU-5 super-off-peak. That is generally the right timing; the next optimization is checking whether the battery also grid-charges then and whether simultaneous loads create avoidable peaks.`},
 {p:2,t:'Summer exports are doing real work',d:'April through July reduced the running NEM balance by about $270. The system should forecast whether August–October can erase more before true-up rather than showing only a static balance.'},
 {p:3,t:'Build whole-home load attribution next',d:`The supplied Emporia export contains the EV charger only. To say where every kWh went, Build 2 should ingest the rest of the Emporia circuits or a whole-home main feed.`},
 {p:3,t:'Battery behavior can become an optimization layer',d:`The Tesla export shows net Powerwall charging of about ${num(Math.abs(t['Powerwall (kW)']),1)} kWh across the supplied window. Once tariff and reserve settings are connected, the brain can score whether charge/discharge timing is financially optimal.`}
]}
function renderInsights(){const arr=getInsights();$('#insightList').innerHTML=arr.map(i=>`<article class="card insight"><span class="priority">P${i.p}</span><div class="eyebrow">SMART FINDING</div><h3>${i.t}</h3><p>${i.d}</p></article>`).join('')}
function renderConnections(){const rows=[['⚡','SDG&E','Bill + NEM + TOU','Loaded'],['▰','Tesla Powerwall','5-minute site telemetry','Loaded'],['🔌','Emporia','EV circuit export','Loaded'],['☀️','SolarEdge','Production snapshot','Partial'],['◉','Enphase Enlighten','Detected in smart-home stack','Not connected'],['⌂','Nest / HVAC','Future load context','Not connected'],['🚘','EV / Tesla vehicle','Future charging context','Not connected'],['☁️','Ambient Weather','Future weather correlation','Not connected']];$('#connectionsList').innerHTML=rows.map(r=>`<article class="card connection"><div class="icon">${r[0]}</div><div class="meta"><b>${r[1]}</b><span>${r[2]}</span></div><span class="tag">${r[3]}</span></article>`).join('')}
$$('.nav').forEach(b=>b.onclick=()=>{$$('.nav,.view').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.view).classList.add('active');$('#page-title').textContent=b.querySelector('span').textContent;setTimeout(()=>{if(b.dataset.view==='overview'){drawNem();drawTesla()}if(b.dataset.view==='audit')drawDonut();if(b.dataset.view==='flows')drawEv()},10)});
$('#refresh').onclick=()=>load(); $('#sortInsights').onclick=()=>renderInsights();
$('#csvUpload').addEventListener('change',async ev=>{const f=ev.target.files[0];if(!f)return;const text=await f.text(),lines=text.trim().split(/\r?\n/),headers=lines[0].split(',');$('#uploadResult').textContent=`${f.name}\n${lines.length-1} data rows\nColumns: ${headers.join(' · ')}\n\nLocal inspection only — no upload performed.`});
window.addEventListener('resize',()=>{if(DATA.bill){if($('#overview').classList.contains('active')){drawNem();drawTesla()}if($('#audit').classList.contains('active'))drawDonut();if($('#flows').classList.contains('active'))drawEv()}});
load();
