name = "energy-daddy-api"
main = "src/worker.js"
compatibility_date = "2026-08-19"
workers_dev = true
preview_urls = false

[assets]
directory = "./public"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "ENERGY_DB"
database_name = "energy-daddy-db"
database_id = "700aac7e-8e88-4e4a-a95f-13698e9ce2e5"
migrations_dir = "migrations"

[[kv_namespaces]]
binding = "ENERGY_STATE"
id = "fd34603a791348e682a341c577352b25"

[vars]
APP_ENV = "production"
ALLOWED_ORIGINS = ""
SOLAREDGE_SITE_ID = ""
ENPHASE_SYSTEM_ID = "5484185"

[triggers]
crons = ["*/15 * * * *"]
